namespace RunLoki365.Models;

/// <summary>
/// Application version information.
/// </summary>
public static class VersionInfo
{
    /// <summary>
    /// Semantic version number.
    /// </summary>
    public const string Version = "1.0.0";

    /// <summary>
    /// Version name/codename.
    /// </summary>
    public const string VersionName = "Loki";

    /// <summary>
    /// GitHub repository URL.
    /// </summary>
    public const string GitHubUrl = "https://github.com/mohamedEmad23/RunLoki365";

    /// <summary>
    /// License type.
    /// </summary>
    public const string License = "MIT";

    /// <summary>
    /// Copyright information.
    /// </summary>
    public const string Copyright = "Copyright © 2025 mohamedEmad23";

    /// <summary>
    /// Gets the full version string.
    /// </summary>
    public static string FullVersion => $"{Version} ({VersionName})";

    /// <summary>
    /// Gets the build date from the assembly.
    /// </summary>
    public static string BuildDate
    {
        get
        {
            var assemblyPath = AppContext.BaseDirectory;
            var mainAssembly = Path.Combine(assemblyPath, "runloki365.dll");
            if (File.Exists(mainAssembly))
            {
                return File.GetLastWriteTime(mainAssembly).ToString("yyyy-MM-dd HH:mm");
            }
            return "Unknown";
        }
    }

    /// <summary>
    /// Gets the commit hash if available (set during build).
    /// </summary>
    public static string CommitHash =>
        ThisAssembly.Git.Commit ?? "dev";

    /// <summary>
    /// Gets whether this is a dirty build (uncommitted changes).
    /// </summary>
    public static bool IsDirtyBuild =>
        ThisAssembly.Git.IsDirty;
}

/// <summary>
/// Git metadata injected at build time.
/// This class will be auto-generated by GitInfo NuGet package.
/// </summary>
internal static class ThisAssembly
{
    internal static class Git
    {
        // These will be populated by GitInfo package at build time
        // For now, provide fallback values
        internal static string? Commit => Environment.GetEnvironmentVariable("GIT_COMMIT");
        internal static bool IsDirty => !string.IsNullOrEmpty(Environment.GetEnvironmentVariable("GIT_DIRTY"));
    }
}
